import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/ui/Navbar";

const PoppinsSans = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased">
      <body className={`${PoppinsSans.className} min-h-full flex flex-col overflow-x-hidden`}>
        <Navbar />
        <main className="flex w-full flex-col min-h-screen">
          {children}
        </main>
      </body>
    </html>
  );
}
